spring:
  rabbitmq:
    host: 192.168.0.147
    port: 5672
    username: lyh
    password: aaa111
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 把消息确认模式改为手动确认
        prefetch: 1 # 设置每次最多从消息队列服务器取回多少消息
logging:
  level:
    com.at2024.springboot_consumer.mq.listener.MyMessageListener: info